name: "Sync from remote"

on: "workflow_dispatch"

jobs:

  github-sync:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
      with:
        persist-credentials: false
    - name: "Bypass Cloudflare for GitHub Action"
      uses: "xiaotianxt/bypass-cloudflare-for-github-action@v1.1.1"
      with:
        cf_zone_id: "${{ secrets.CF_ZONE_ID }}"
        cf_api_token: "${{ secrets.CF_API_TOKEN }}"
    - name: "Github Sync"
      uses: "repo-sync/github-sync@v2"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        source_repo: "https://${{ secrets.ACCESS_TOKEN }}@code.a76a6a65.nexus/a76a6a65/dotnet-Svg.Contrib.Render.git"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: true
